In [3]:
import numpy as mp
import pandas as pd

In [4]:
df=pd.read_csv('heart.csv')

In [5]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [6]:
x=df.iloc[:,0:-1]
y=df.iloc[:,-1]

In [7]:
x.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [8]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [9]:
df.shape

(303, 14)

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [12]:
lr=LogisticRegression()
dt=DecisionTreeClassifier()

In [13]:
lr.fit(x_train,y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [14]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [15]:
y_pred1=lr.predict(x_test)
y_pred2=dt.predict(x_test)

In [16]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("accuracy score of logistic regression : ",accuracy_score(y_test,y_pred1))
print("accuracy score of decision tree : ",accuracy_score(y_test,y_pred2))

accuracy score of logistic regression :  0.9016393442622951
accuracy score of decision tree :  0.8524590163934426

In [17]:
confusion_matrix(y_test,y_pred1)

array([[26,  6],
       [ 0, 29]])

In [18]:
confusion_matrix(y_test,y_pred2)

array([[24,  8],
       [ 1, 28]])

In [19]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [20]:
print("for logistic regression model")
print("-"*50)
dff=pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(dff)
print("-"*50)
print("precision : ",precision_score(y_test,y_pred1))
print("recall : ",recall_score(y_test,y_pred1))
print("f1 score : ",f1_score(y_test,y_pred1))

for logistic regression model
--------------------------------------------------
    0   1
0  26   6
1   0  29
--------------------------------------------------
precision :  0.8285714285714286
recall :  1.0
f1 score :  0.90625

In [21]:
print("for DecisionTreeClassifier model ")
print("-"*50)
dff=pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(dff)
print("-"*50)
print("precision : ",precision_score(y_test,y_pred2))
print("recall : ",recall_score(y_test,y_pred2))
print("f1 score : ",f1_score(y_test,y_pred2))

for DecisionTreeClassifier model
--------------------------------------------------
    0   1
0  24   8
1   1  28
--------------------------------------------------
precision :  0.7777777777777778
recall :  0.9655172413793104
f1 score :  0.8615384615384616

In [22]:
df1=pd.read_csv("train.csv")
df1

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41996,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41997,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41998,6,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
41999,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
x1=df1.iloc[:,1:]
y1=df1.iloc[:,0]

In [24]:
from sklearn.model_selection import train_test_split
x1_train,x1_test,y1_train,y1_test=train_test_split(x1,y1,test_size=0.2,random_state=2)

In [25]:
lor=LogisticRegression()
Dt=DecisionTreeClassifier()

In [26]:
lor.fit(x1_train,y1_train)
Dt.fit(x1_train,y1_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [27]:
y1_pred1=lor.predict(x1_test)
y1_pred2=Dt.predict(x1_test)

In [28]:
cfd=pd.DataFrame(confusion_matrix(y1_test,y1_pred1),columns=list(range(0,10)))
print(cfd)

     0    1    2    3    4    5    6    7    8    9
0  791    0    1    0    1    9   11    1    6    1
1    0  938    2    4    0    3    0    3   12    0
2    2    9  745   16    9    4   13   13   15    3
3    1    4   19  763    0   36    5    5   20   11
4    2    5    4    0  804    1    7    3    9   21
5    9    3    4   23   10  610   15   10   34   11
6   12    4   12    1    7    8  789    0    5    1
7    3    2   13    6    4    2    0  812    2   29
8   11   12   13   18    1   21    6    6  694   11
9    3    6    2   14   25    4    0   37    7  736

In [29]:
dtf=pd.DataFrame(confusion_matrix(y1_test,y1_pred2),columns=list(range(0,10)))
print(dtf)

     0    1    2    3    4    5    6    7    8    9
0  759    3    9    3    2   16   13    1    9    6
1    0  899   11    9    8    7    7    6   13    2
2    9   19  672   32   15   13   17   20   24    8
3    7   14   34  683    9   51    7   15   29   15
4    8    7   11    5  740    6   13    9   16   41
5   16    5   11   44   10  578   18    8   22   17
6   15    1   10    3    9   24  758    0   15    4
7    3   10   21   18    8    6    2  773   11   21
8   12   19   20   37   18   33   15    7  613   19
9    5    4    8   15   43   15    4   28   19  693

In [30]:
precision_score(y1_test,y1_pred1,average=None)

array([0.94844125, 0.95422177, 0.91411043, 0.90295858, 0.93379791,
       0.8739255 , 0.93262411, 0.91235955, 0.86318408, 0.89320388])

In [31]:
recall_score(y1_test,y1_pred1,average=None)

array([0.9634592 , 0.97505198, 0.8986731 , 0.88310185, 0.93925234,
       0.83676269, 0.94040524, 0.930126  , 0.87515763, 0.882494  ])

In [32]:
f1_score(y1_test,y1_pred1,average=None)

array([0.95589124, 0.96452442, 0.90632603, 0.89291984, 0.93651718,
       0.85494043, 0.93649852, 0.92115712, 0.86912962, 0.88781665])

In [33]:
precision_score(y1_test,y1_pred2,average=None)

array([0.91007194, 0.91641182, 0.83271375, 0.80447585, 0.85846868,
       0.77169559, 0.88758782, 0.89158016, 0.79507134, 0.83898305])

In [34]:
recall_score(y1_test,y1_pred2,average=None)

array([0.92448234, 0.93451143, 0.8106152 , 0.79050926, 0.86448598,
       0.79286694, 0.9034565 , 0.88545246, 0.77301387, 0.83093525])

In [35]:
f1_score(y1_test,y1_pred2,average=None)

array([0.91722054, 0.92537313, 0.82151589, 0.79743141, 0.86146682,
       0.78213802, 0.89545186, 0.88850575, 0.78388747, 0.83493976])

In [36]:
recall_score(y1_test,y1_pred1,average='macro')

0.9124484028871509

In [37]:
recall_score(y1_test,y1_pred1,average='weighted')

0.9145238095238095

In [38]:
from sklearn.metrics import classification_report
print(classification_report(y1_test,y1_pred1))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       821
           1       0.95      0.98      0.96       962
           2       0.91      0.90      0.91       829
           3       0.90      0.88      0.89       864
           4       0.93      0.94      0.94       856
           5       0.87      0.84      0.85       729
           6       0.93      0.94      0.94       839
           7       0.91      0.93      0.92       873
           8       0.86      0.88      0.87       793
           9       0.89      0.88      0.89       834

    accuracy                           0.91      8400
   macro avg       0.91      0.91      0.91      8400
weighted avg       0.91      0.91      0.91      8400

In [39]:
print(classification_report(y1_test,y1_pred2))

              precision    recall  f1-score   support

           0       0.91      0.92      0.92       821
           1       0.92      0.93      0.93       962
           2       0.83      0.81      0.82       829
           3       0.80      0.79      0.80       864
           4       0.86      0.86      0.86       856
           5       0.77      0.79      0.78       729
           6       0.89      0.90      0.90       839
           7       0.89      0.89      0.89       873
           8       0.80      0.77      0.78       793
           9       0.84      0.83      0.83       834

    accuracy                           0.85      8400
   macro avg       0.85      0.85      0.85      8400
weighted avg       0.85      0.85      0.85      8400

In [46]:
query=mp.array([[mp.random.randint(0,2) for i in range(784)]])

In [47]:
query

array([[1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
        1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
        1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
        1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
        0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
        0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
        1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
        0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
        1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
        1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
        0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
        0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
        1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
        1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
        0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
        0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
        1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
        0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
        0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
        0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1]])

In [48]:
lor.predict_proba(query)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[0.09681829, 0.09014676, 0.11165965, 0.11191541, 0.08467438,
        0.11228999, 0.10086484, 0.09472412, 0.10214404, 0.09476254]])

In [49]:
lor.predict(query)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([5])